### ISSUE TITLE
Popup tram_stop

### ISSUE THREAD

**Issue by RailMapper** [hiddewie/OpenRailwayMap-vector#107]
The popup clicking at the elements (nodes) with the tags 
public_transport=stop_position
railway=tram_stop
tram=yes
is empty. See [https://openrailwaymap.fly.dev/#view=18/52.385962/4.84609&style=standard](url) for tram_stop Molenwerf.

**Comment by hiddewie** [comment]
Thanks for the issue. This is true. 

The popups on the map for features are relatively new, and a lot of information is still missing from the popups. The rail lines have most information filled in, while almost all other features on the map are missing information.

This needs work.

**Comment by hiddewie** [comment]
I started some work in #152 to identify every feature in every layer properly in the UI. Definitely not ready yet, but in progress.

**Comment by hiddewie** [comment]
https://github.com/hiddewie/OpenRailwayMap-vector/pull/152 is merged. It ensures tram stops correctly show the name, and are clustered together if multiple tram stops share the same name.

I will verify if this solves the issue entirely.

**Comment by hiddewie** [comment]
Before

![image](https://github.com/user-attachments/assets/148bdc8e-d389-4cb5-acf2-a55f104083af)

After

![image](https://github.com/user-attachments/assets/dc7f495a-5306-48ff-88fa-6a9528752b70)

**Comment by RailMapper** [comment]
Thanks for changing. Clicking a tram_stop shows a popup as shown in your figure without the tags. But clicking the way shows the whole information in all the tags.
![tram_way](https://github.com/user-attachments/assets/d540ba80-1b6d-4ca4-a1d9-dd002bad6949)
By the way - I know the tram's line numbers are stored in the OSM data in relations. I'm tinkering for my own around tram networks for offline maps and the target is to show the line number in the popup of a tram_stop. The extraction of line numbers works but the popup does still not. It's for your information and not an issue.

**Comment by hiddewie** [comment]
Yes the line has information about the tram line, the tram stop by itself does not have much information imported at the moment.

> I know the tram's line numbers are stored in the OSM data in relations. I'm tinkering for my own around tram networks for offline maps and the target is to show the line number in the popup of a tram_stop.

This is great! In general it would be great to store additional information on stations / tram stops about the routes that use that station.

I would also like to create a separate visual layer showing every rail route, in a metro style. In the metro-style like https://parisbytrain.com/paris-metro-maps. But this is not easy to get right visually because many rail routes use the same railway lines.

![image](https://github.com/user-attachments/assets/2bc9aec8-19df-4739-af3d-d59cf69ff030)

Any input is welcome!
