### ISSUE TITLE
Allow changing the background map

### ISSUE THREAD

**Issue by hiddewie** [hiddewie/OpenRailwayMap-vector#66]
- [x] no background map
- [x] grayscale map
- [x] color map
- [x] half-grayscale map
- [ ] other vector map (from URL, store in local storage)
- [x] other raster map (from URL, store in local storage)

**Comment by hlfan** [comment]
These options should be combinable so that for all map sources (standard or custom) the three grayscale levels (0%, 50%, 100%) can be set.
Also in the wake of this, the standard map could be changed to an OSM vector map, whether future OSMF or third-party tiles like [this](https://www.maptiler.com/maps/#style=openstreetmap).

**Comment by hiddewie** [comment]
Thanks for the comment. https://github.com/hiddewie/OpenRailwayMap-vector/pull/68 contains basic configuration for saturation, opacity and raster tile URL.

Supporting vector tiles as a background map layer requires more work.

**Comment by hiddewie** [comment]
Vector background map is implemented in https://github.com/hiddewie/OpenRailwayMap-vector/pull/109
