### ISSUE TITLE
how can i change the region displayed？

### ISSUE THREAD

**Issue by Asatoshi314** [hiddewie/OpenRailwayMap-vector#99]
i imported OSM data of North America but after I have followed setup instruction the map still displays Europe，how can i fix this？

**Comment by wolfy1339** [comment]
In the `proxy/js/ui.js` file.
https://github.com/hiddewie/OpenRailwayMap-vector/blob/db203b5308afcd6c86fcf9dfa405f81a90682249/proxy/js/ui.js#L257

In my fork, I added some North American features, https://github.com/hiddewie/OpenRailwayMap-vector/compare/master...wolfy1339:OpenRailwayMap-vector:master?expand=1

**Comment by wolfy1339** [comment]
In my testing, you can browse the map locally just fine, exporting the tiles for serving them takes upwards of 8 hours for each style for the North America region

**Comment by Asatoshi314** [comment]
> In the `proxy/js/ui.js` file.
> 
> https://github.com/hiddewie/OpenRailwayMap-vector/blob/db203b5308afcd6c86fcf9dfa405f81a90682249/proxy/js/ui.js#L257
> 
> In my fork, I added some North American features, https://github.com/hiddewie/OpenRailwayMap-vector/compare/master...wolfy1339:OpenRailwayMap-vector:master?expand=1

haha, i just found tihs out by myself, thanks bro!

**Comment by hiddewie** [comment]
Thanks for the comments. I think it would be useful to let the database store the extend of imported data, and let the UI render that. 

The current hardcoded map bounds are only because currently I focus on Europe, there is a lot to be gained there in visualizing existing data. Currently the deployed variant https://openrailwaymap.fly.dev/ only covers Europe because I do not have access to server capacity to render the entire world with daily updates.

However, this project should work for everybody, so the UI should adapt to whatever data has been imported.

**Comment by hiddewie** [comment]
> In my fork, I added some North American features, https://github.com/hiddewie/OpenRailwayMap-vector/compare/master...wolfy1339:OpenRailwayMap-vector:master?expand=1

This is great, feel free to contribute separate features such as support for `reporting_marks` and `track_class` in pull requests!

**Comment by hiddewie** [comment]
I made https://github.com/hiddewie/OpenRailwayMap-vector/pull/102 to take the bounds of the imported data into account in the UI, if that information is available. Otherwise, the entire map is shown in the UI.
